/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursify.view;

import coursify.view.admin.AdminMainFrame;
import coursify.view.tutor.TutorMainFrame;
import coursify.database.DataStore;
import coursify.model.User;
import coursify.model.Tutor;
import coursify.model.Admin;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.SwingUtilities;
import java.awt.event.ActionListener; 
import java.util.logging.Level;

/**
 *
 * @author Indosmart CT
 */
public class Login extends javax.swing.JFrame {
    
    private static final Color SUCCESS_COLOR = new Color(39, 174, 96);
    private static final Color ERROR_COLOR = new Color(231, 76, 60);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(360, 440);               // ← Set ukuran eksplisit
        this.setLocationRelativeTo(null);
         this.setResizable(false); 
       
    pemberitahuan.setText("Silakan masukkan Username dan Password Anda"); 
    pemberitahuan.setForeground(Color.DARK_GRAY); 
    pemberitahuan.setFont(new java.awt.Font("Tw Cen MT", 0, 12));
    
    LoginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 performLogin();
            }
    });
        
    // Tambahkan listener untuk tombol Enter pada password field
    PasswoardField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 performLogin();
            }
        });
    }
    
    private void performLogin() {
        String username = UsernameField.getText().trim();
        // Catatan: Gunakan PasswoardField (dengan double 'a') sesuai deklarasi NetBeans
        String password = new String(PasswoardField.getPassword());
        
        if (username.isEmpty() || password.isEmpty()) {
            pemberitahuan.setText("Username dan password tidak boleh kosong!");
            pemberitahuan.setForeground(ERROR_COLOR);
            return;
        }
        
        // Cari user di DataStore (Menggunakan kelas DataStore dari file yang Anda unggah)
        User user = DataStore.getUser(username, password);
        
        if (user != null) {
            // Login berhasil
            pemberitahuan.setText("Login berhasil! Selamat datang " + user.getUsername());
            pemberitahuan.setForeground(SUCCESS_COLOR);
            
            // Polymorphism: Tampilkan frame yang sesuai berdasarkan role
            SwingUtilities.invokeLater(() -> {
                if (user instanceof Admin) {
                    // Jika Admin, tampilkan AdminMainFrame
                    AdminMainFrame adminFrame = new AdminMainFrame((Admin) user);
                    adminFrame.setVisible(true);
                } else if (user instanceof Tutor) {
                    // Jika Tutor, tampilkan TutorMainFrame
                    TutorMainFrame tutorFrame = new TutorMainFrame((Tutor) user);
                    tutorFrame.setVisible(true);
                }
                dispose(); // Tutup login frame
            });
        } else {
            // Login gagal
            pemberitahuan.setText("Username atau password salah!");
            pemberitahuan.setForeground(ERROR_COLOR);
            PasswoardField.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cousify = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        pemberitahuan = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        Passwoard = new javax.swing.JLabel();
        PasswoardField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(27, 60, 83));

        Cousify.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Cousify.setForeground(new java.awt.Color(242, 242, 242));
        Cousify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cousify.setText("Coursify");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cousify, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Cousify)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 50);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        Welcome.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("WELCOME !");

        pemberitahuan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        pemberitahuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemberitahuan.setText("Please insert your Username and Password");

        Username.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Username.setText("Username");

        UsernameField.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        Passwoard.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Passwoard.setText("Passwoard");

        LoginButton.setBackground(new java.awt.Color(69, 104, 130));
        LoginButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(242, 242, 242));
        LoginButton.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameField))
                            .addComponent(pemberitahuan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Passwoard, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(PasswoardField))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemberitahuan)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswoardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Passwoard))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 360, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed
    
    private void Login() {
        String username = UsernameField.getText().trim();
        String password = new String(PasswoardField.getPassword());
        
        if (username.isEmpty() || password.isEmpty()) {
            pemberitahuan.setText("Username dan password tidak boleh kosong!");
            pemberitahuan.setForeground(ERROR_COLOR);
            return;
        }
        
        // Cari user di DataStore
        User user = DataStore.getUser(username, password);
        
        if (user != null) {
            // Login berhasil
            pemberitahuan.setText("Login berhasil! Selamat datang " + user.getUsername());
            pemberitahuan.setForeground(SUCCESS_COLOR);
            
            // Polymorphism: Tampilkan frame yang sesuai berdasarkan role
            SwingUtilities.invokeLater(() -> {
                if (user instanceof Admin) {
                    // Jika Admin, tampilkan AdminMainFrame
                    AdminMainFrame adminFrame = new AdminMainFrame((Admin) user);
                    adminFrame.setVisible(true);
                } else if (user instanceof Tutor) {
                    // Jika Tutor, tampilkan TutorMainFrame
                    TutorMainFrame tutorFrame = new TutorMainFrame((Tutor) user);
                    tutorFrame.setVisible(true);
                }
                dispose(); // Tutup login frame
            });
        } else {
            // Login gagal
            pemberitahuan.setText("Username atau password salah!");
            pemberitahuan.setForeground(ERROR_COLOR);
            PasswoardField.setText("");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cousify;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Passwoard;
    private javax.swing.JPasswordField PasswoardField;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pemberitahuan;
    // End of variables declaration//GEN-END:variables
}
